# Generated by Django 3.1.6 on 2021-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_img',
            field=models.ImageField(default='images/profile.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
