# Generated by Django 3.1.6 on 2021-06-10 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0002_auto_20210610_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateTimeField(default=datetime.date(2021, 6, 10)),
        ),
    ]
