# Generated by Django 3.1.6 on 2021-06-10 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0004_userinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
