# Generated by Django 3.1.6 on 2021-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0006_auto_20210610_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_img',
            field=models.ImageField(default='images/profile.jpg', upload_to='images/'),
        ),
    ]
