# Generated by Django 3.1.6 on 2021-06-10 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0007_auto_20210610_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('reciever_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateTimeField(default=datetime.date(2021, 6, 11)),
        ),
    ]
